"use client";

import { Bookmark, Check, CheckCircle2, LoaderCircle, MessageSquareText, Star, X, XCircle, Zap } from "lucide-react";
import { useState } from "react";
import type { QuestionChoiceMap, QuestionResult, QuestionType } from "@/lib/question-bank";

type QuestionCardData={
  statement:string; question_type:QuestionType; choices:QuestionChoiceMap|null; level:number; banca:string|null; ano:number|null; exam_name:string|null;
  subject_name?:string|null; lesson_title?:string|null; selected_answer?:string|null; is_correct?:boolean|null; correct_answer?:string|null; explanation?:string|null; starred?:boolean; saved_for_review?:boolean;
};

export function QuestionCard({question,number,onAnswer,onToggleMark,compact=false,hidePreviousResolution=false}:{question:QuestionCardData;number:number;onAnswer:(answer:string)=>Promise<QuestionResult>;onToggleMark?:(mark:"starred"|"review",value:boolean)=>Promise<{starred:boolean;saved_for_review:boolean}>;compact?:boolean;hidePreviousResolution?:boolean}){
  const [selected,setSelected]=useState(hidePreviousResolution?"":(question.selected_answer??""));
  const [result,setResult]=useState<QuestionResult|null>(!hidePreviousResolution&&question.selected_answer&&question.is_correct!==null&&question.is_correct!==undefined?{is_correct:question.is_correct,correct_answer:question.correct_answer??"",explanation:question.explanation??null}:null);
  const [submitting,setSubmitting]=useState(false);const [marking,setMarking]=useState<"starred"|"review"|null>(null);const [starred,setStarred]=useState(Boolean(question.starred));const [saved,setSaved]=useState(Boolean(question.saved_for_review));const [showExplanation,setShowExplanation]=useState(false);const [error,setError]=useState<string|null>(null);const [nonce,setNonce]=useState(0);
  const options=question.question_type==="true_false"?[["TRUE","Certo"],["FALSE","Errado"]]:Object.entries(question.choices??{}).sort(([a],[b])=>a.localeCompare(b));

  function choose(value:string){if(submitting||result)return;setSelected(value);setShowExplanation(false)}
  async function answer(){if(!selected||submitting||result)return;setSubmitting(true);setError(null);try{const next=await onAnswer(selected);setResult(next);setNonce(v=>v+1);}catch(e){setError(e instanceof Error?e.message:"Não foi possível corrigir a resposta.");}finally{setSubmitting(false)}}
  async function toggle(mark:"starred"|"review"){if(!onToggleMark||marking)return;const nextValue=mark==="starred"?!starred:!saved;setMarking(mark);try{const next=await onToggleMark(mark,nextValue);setStarred(next.starred);setSaved(next.saved_for_review);}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar a marcação.");}finally{setMarking(null)}}

  const feedback=result?(result.is_correct?"mt-question-correct-pop":"mt-question-wrong-shake"):"";
  return <article key={nonce} className={`relative overflow-hidden rounded-[24px] border bg-[var(--surface)] p-5 transition sm:p-7 ${feedback} ${result?.is_correct?"border-emerald-400/30":result&&!result.is_correct?"border-red-400/30":"border-[var(--border)]"}`}>
    {result?<div className={`absolute inset-x-0 top-0 h-1 ${result.is_correct?"bg-emerald-400":"bg-red-400"}`}/>:null}
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--border)] pb-4"><div className="flex flex-wrap items-center gap-2 text-[9px] font-black tracking-[.1em] text-[var(--muted)]"><span className="rounded-full border border-violet-400/20 bg-violet-400/[.07] px-3 py-1.5 text-violet-300">QUESTÃO {String(number).padStart(2,"0")}</span>{question.banca?<span>{question.banca}</span>:null}{question.ano?<span>· {question.ano}</span>:null}{question.exam_name?<span>· {question.exam_name}</span>:null}</div><div className="flex items-center gap-2">{onToggleMark?<button onClick={()=>toggle("review")} disabled={Boolean(marking)} className={`inline-flex h-9 items-center gap-2 rounded-xl border px-3 text-[8px] font-black ${saved?"border-violet-400/35 bg-violet-400/10 text-violet-300":"border-[var(--border)] text-[var(--muted)]"}`}><Bookmark size={13} fill={saved?"currentColor":"none"}/>{saved?"NA REVISÃO":"REVISAR"}</button>:null}{onToggleMark?<button onClick={()=>toggle("starred")} disabled={Boolean(marking)} className={`grid h-9 w-9 place-items-center rounded-xl border ${starred?"border-violet-400/35 bg-violet-400/10 text-violet-300":"border-[var(--border)] text-[var(--muted)]"}`}><Star size={15} fill={starred?"currentColor":"none"}/></button>:null}<span className="rounded-full border border-[var(--border)] px-3 py-1.5 text-[8px] font-black text-violet-300">NÍVEL {question.level}</span></div></div>
    {question.subject_name||question.lesson_title?<div className="mt-4 flex flex-wrap gap-2 text-[10px] font-bold text-[var(--muted)]">{question.subject_name?<span>{question.subject_name}</span>:null}{question.lesson_title?<span>→ {question.lesson_title}</span>:null}</div>:null}
    <p className="mt-5 whitespace-pre-wrap text-[15px] leading-7 text-[var(--ink)] sm:text-base">{question.statement}</p>

    {question.question_type==="true_false"?<div className="mt-6 inline-flex max-w-full rounded-[16px] border border-[var(--border)] bg-[var(--background)] p-1.5">{options.map(([value,label])=>{const checked=selected===value;const correct=result?.correct_answer===value;const wrong=Boolean(result&&!result.is_correct&&checked);const isTrue=value==="TRUE";return <button key={value} type="button" onClick={()=>choose(value)} disabled={submitting||Boolean(result)} className={`flex min-h-10 min-w-[118px] items-center justify-center gap-2 rounded-xl px-4 text-[12px] font-black transition ${checked&&!result?"bg-violet-500 text-white shadow-[0_8px_24px_rgba(124,58,237,.22)]":"text-[var(--muted)] hover:bg-white/[.03]"}`} style={result?{background:correct?"rgba(34,197,94,.12)":wrong?"rgba(239,68,68,.12)":undefined,color:correct?"#4ade80":wrong?"#f87171":undefined}:undefined}><span className={`grid h-6 w-6 place-items-center rounded-lg ${isTrue?"text-emerald-400":"text-red-400"}`}>{isTrue?<Check size={16}/>:<X size={16}/>}</span>{label}</button>})}</div>:
      <div className="mt-6 grid gap-2.5">{options.map(([value,label])=>{const checked=selected===value;const correct=result?.correct_answer===value;const wrong=Boolean(result&&!result.is_correct&&checked);return <button key={value} type="button" onClick={()=>choose(value)} disabled={submitting||Boolean(result)} className={`group flex w-full items-start gap-3 rounded-[16px] border p-4 text-left transition ${checked&&!result?"border-violet-400/55 bg-violet-400/[.085] shadow-[0_10px_30px_rgba(124,58,237,.08)]":"border-[var(--border)] bg-[var(--background)] hover:border-violet-400/28 hover:bg-violet-400/[.035]"}`} style={result?{borderColor:correct?"rgba(34,197,94,.48)":wrong?"rgba(239,68,68,.48)":"var(--border)",background:correct?"rgba(34,197,94,.07)":wrong?"rgba(239,68,68,.07)":"var(--background)"}:undefined}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl border text-[12px] font-black ${checked&&!result?"border-violet-300/50 bg-violet-500 text-white":"border-[var(--border)] text-violet-300"}`} style={result?{borderColor:correct?"rgba(34,197,94,.45)":wrong?"rgba(239,68,68,.45)":"var(--border)",color:correct?"#4ade80":wrong?"#f87171":undefined}:undefined}>{value}</span><span className="pt-1.5 text-sm leading-6 text-[var(--ink)]">{label}</span>{correct?<CheckCircle2 className="ml-auto mt-1.5 shrink-0 text-emerald-400" size={18}/>:wrong?<XCircle className="ml-auto mt-1.5 shrink-0 text-red-400" size={18}/>:null}</button>})}</div>}

    <div className="mt-5 flex flex-wrap items-center gap-3"><button onClick={answer} disabled={!selected||submitting||Boolean(result)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-violet-600 px-5 text-[10px] font-black tracking-[.1em] text-white transition hover:bg-violet-500 disabled:cursor-not-allowed disabled:opacity-45">{submitting?<LoaderCircle className="animate-spin" size={15}/>:<CheckCircle2 size={15}/>} {result?"RESPONDIDA":"CONFIRMAR RESPOSTA"}</button>{result?<span className={`inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 text-[10px] font-black ${result.is_correct?"border-emerald-400/30 bg-emerald-400/10 text-emerald-400":"border-red-400/30 bg-red-400/10 text-red-400"}`}>{result.is_correct?<CheckCircle2 size={17}/>:<XCircle size={17}/>} {result.is_correct?"ACERTOU":"ERROU"}<span className="ml-1 inline-flex items-center gap-1 rounded-lg bg-black/10 px-2 py-1"><Zap size={12}/>{result.is_correct?"+12 XP":"+4 XP"}</span></span>:null}</div>
    {error?<p className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-xs text-red-400">{error}</p>:null}
    {result?<div className={`mt-5 rounded-2xl border p-4 sm:p-5 ${result.is_correct?"border-emerald-400/20 bg-emerald-400/[.045]":"border-red-400/20 bg-red-400/[.045]"}`}><span className={`text-[9px] font-black tracking-[.14em] ${result.is_correct?"text-emerald-400":"text-red-400"}`}>GABARITO · {formatAnswer(result.correct_answer,question.question_type)}</span><button onClick={()=>setShowExplanation(v=>!v)} className="mt-3 flex min-h-10 items-center gap-2 rounded-xl border border-[var(--border)] px-3 text-[9px] font-black text-[var(--muted)]"><MessageSquareText size={14}/>{showExplanation?"FECHAR COMENTÁRIO":"ABRIR COMENTÁRIO"}</button>{showExplanation?<p className="mt-3 border-t border-[var(--border)] pt-3 text-xs leading-6 text-[var(--muted)]">{result.explanation||"Questão corrigida. Comentário ainda não cadastrado."}</p>:null}</div>:null}
    <style jsx global>{`@keyframes mtCorrectPop{0%{transform:scale(1)}45%{transform:scale(1.008);box-shadow:0 0 0 4px rgba(34,197,94,.08)}100%{transform:scale(1)}}@keyframes mtWrongShake{0%,100%{transform:translateX(0)}25%{transform:translateX(-4px)}50%{transform:translateX(4px)}75%{transform:translateX(-2px)}}.mt-question-correct-pop{animation:mtCorrectPop .46s ease}.mt-question-wrong-shake{animation:mtWrongShake .38s ease}`}</style>
  </article>
}
function formatAnswer(answer:string,type:QuestionType){if(type==="true_false")return answer==="TRUE"?"CERTO":"ERRADO";return answer||"—"}
