export type Priority = "Média" | "Média/alta" | "Alta" | "Muito alta" | "Muito alta para PRF";

export interface MatrixLesson {
  id: number;
  slug: string;
  title: string;
  topics: string[];
  priority: Priority;
  weekOne: boolean;
  questionCount?: number;
}

export interface PrfSubject {
  slug: string;
  shortName: string;
  name: string;
  description: string;
  lessons: MatrixLesson[];
}

export const accountingLessons: MatrixLesson[] = [
  {
    id: 1,
    slug: "fundamentos-da-contabilidade",
    title: "Fundamentos da Contabilidade",
    topics: [
      "conceito",
      "objeto",
      "objetivo",
      "finalidade",
      "patrimônio como objeto",
      "campo de aplicação",
      "usuários da informação contábil",
    ],
    priority: "Média",
    weekOne: true,
  },
  {
    id: 2,
    slug: "patrimonio-e-situacao-liquida",
    title: "Patrimônio e Situação Líquida",
    topics: [
      "ativo",
      "passivo",
      "patrimônio líquido",
      "bens, direitos e obrigações",
      "equação fundamental",
      "patrimônio bruto",
      "patrimônio líquido",
      "situação líquida positiva, negativa e nula",
      "ativo a descoberto/passivo a descoberto",
      "representação gráfica",
    ],
    priority: "Muito alta",
    weekOne: true,
  },
  {
    id: 3,
    slug: "atos-e-fatos-administrativos",
    title: "Atos e Fatos Administrativos",
    topics: [
      "atos administrativos",
      "fatos contábeis",
      "fatos permutativos",
      "modificativos aumentativos/diminutivos",
      "mistos aumentativos/diminutivos",
      "impacto no PL",
      "identificação prática da natureza do fato",
    ],
    priority: "Muito alta",
    weekOne: true,
  },
  {
    id: 4,
    slug: "contas-contabeis",
    title: "Contas Contábeis",
    topics: [
      "conceito e finalidade",
      "elementos da conta",
      "contas patrimoniais × resultado",
      "ativo, passivo e PL",
      "receitas e despesas",
      "natureza devedora/credora",
      "débito e crédito",
      "saldo devedor/credor",
      "contas retificadoras",
      "contas sintéticas e analíticas",
      "contas unilaterais/bilaterais",
      "teoria das contas apenas no nível útil",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 5,
    slug: "plano-de-contas",
    title: "Plano de Contas",
    topics: [
      "conceito",
      "finalidade",
      "estrutura",
      "elenco de contas",
      "código",
      "função da conta",
      "funcionamento da conta",
      "diferença entre função e funcionamento",
      "contas sintéticas/analíticas",
      "flexibilidade do plano",
      "manual de contas",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 6,
    slug: "escrituracao-contabil",
    title: "Escrituração Contábil",
    topics: [
      "conceito",
      "método das partidas dobradas",
      "débito × crédito",
      "lançamento contábil",
      "elementos essenciais",
      "fórmulas de lançamento",
      "1ª, 2ª, 3ª e 4ª fórmulas",
      "livro Diário",
      "livro Razão",
      "razonetes",
      "lançamentos simples/compostos",
      "erros de escrituração e retificação",
      "estorno",
      "transferência",
      "complementação",
      "ressalva",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 7,
    slug: "regimes-contabeis",
    title: "Regimes Contábeis",
    topics: [
      "regime de competência",
      "regime de caixa",
      "receitas/despesas antecipadas",
      "receitas/despesas incorridas",
      "reconhecimento contábil",
      "apropriação temporal",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 8,
    slug: "operacoes-contabeis-diversas",
    title: "Operações Contábeis Diversas",
    topics: [
      "compras e vendas",
      "à vista e a prazo",
      "juros ativos/passivos",
      "juros a transcorrer",
      "descontos concedidos/obtidos",
      "tributos",
      "aluguéis",
      "folha de pagamento",
      "provisões",
      "variação monetária e cambial",
      "antecipações",
      "adiantamentos",
      "duplicatas",
      "fornecedores/clientes",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 9,
    slug: "imobilizado-e-depreciacao",
    title: "Imobilizado e Depreciação",
    topics: [
      "aquisição",
      "custo",
      "depreciação",
      "depreciação acumulada",
      "natureza das contas",
      "baixa e venda de imobilizado",
      "ganho/perda na alienação",
      "efeitos patrimoniais",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 10,
    slug: "estoques-e-cmv-basico",
    title: "Estoques e CMV — nível básico",
    topics: [
      "compras",
      "vendas",
      "estoque inicial/final",
      "CMV",
      "mercadorias",
      "efeitos das operações sobre patrimônio e resultado",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 11,
    slug: "balancete-de-verificacao",
    title: "Balancete de Verificação",
    topics: [
      "finalidade",
      "elaboração",
      "saldos devedores/credores",
      "balancete de 2, 4, 6 e 8 colunas",
      "identificação de erros",
      "limitações do balancete",
      "total dos débitos = total dos créditos",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 12,
    slug: "balanco-patrimonial",
    title: "Balanço Patrimonial",
    topics: [
      "conceito",
      "finalidade",
      "ativo circulante/não circulante",
      "passivo circulante/não circulante",
      "patrimônio líquido",
      "classificação das contas",
      "estrutura",
      "equação patrimonial",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 13,
    slug: "dre",
    title: "DRE",
    topics: [
      "conceito",
      "finalidade",
      "receitas",
      "despesas",
      "resultado",
      "lucro/prejuízo",
      "encerramento das contas de resultado",
      "ARE",
      "relação DRE × PL",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
];

export const logicLessons: MatrixLesson[] = [
  {
    id: 1,
    slug: "razao-e-proporcao",
    title: "Razão e Proporção",
    topics: [
      "razão",
      "proporção",
      "propriedades",
      "grandezas direta/inversamente proporcionais",
      "divisão proporcional",
    ],
    priority: "Muito alta",
    weekOne: true,
  },
  {
    id: 2,
    slug: "regra-de-tres",
    title: "Regra de Três",
    topics: [
      "simples direta",
      "simples inversa",
      "composta",
      "identificação das grandezas",
    ],
    priority: "Muito alta",
    weekOne: true,
  },
  {
    id: 3,
    slug: "porcentagem",
    title: "Porcentagem",
    topics: [
      "porcentagem básica",
      "aumentos e descontos",
      "variações percentuais",
      "aumentos sucessivos",
      "descontos sucessivos",
      "diferença percentual",
      "fator de multiplicação",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 4,
    slug: "equacoes-do-primeiro-grau",
    title: "Equações do 1º Grau",
    topics: [
      "equações",
      "problemas",
      "tradução do enunciado",
      "sistemas de equações lineares",
      "sistemas 2×2 e situações-problema",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 5,
    slug: "equacoes-do-segundo-grau",
    title: "Equações do 2º Grau",
    topics: ["raízes", "Bhaskara", "soma/produto", "problemas", "análise das soluções"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 6,
    slug: "funcao-afim",
    title: "Função Afim",
    topics: [
      "conceito de função",
      "domínio/imagem no nível necessário",
      "função do 1º grau",
      "coeficientes",
      "zero",
      "crescimento/decrescimento",
      "gráfico",
      "aplicações",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 7,
    slug: "funcao-quadratica",
    title: "Função Quadrática",
    topics: ["gráfico", "concavidade", "raízes", "vértice", "máximo/mínimo", "sinal", "aplicações"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 8,
    slug: "funcao-exponencial",
    title: "Função Exponencial",
    topics: [
      "propriedades de potência",
      "crescimento/decrescimento",
      "equações básicas",
      "leitura gráfica",
      "aplicações",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 9,
    slug: "funcao-logaritmica",
    title: "Função Logarítmica",
    topics: ["definição", "propriedades", "equações simples", "relação exponencial-log", "gráficos/aplicações básicas"],
    priority: "Média/alta",
    weekOne: false,
  },
  {
    id: 10,
    slug: "taxa-de-variacao",
    title: "Taxa de Variação",
    topics: ["comparação entre grandezas", "taxa média", "razão", "proporcionalidade", "interpretação em problemas"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 11,
    slug: "sequencias-e-padroes",
    title: "Sequências e Padrões",
    topics: ["reconhecimento de padrões", "sequências numéricas", "termo seguinte", "lei de formação"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 12,
    slug: "progressao-aritmetica",
    title: "Progressão Aritmética",
    topics: ["termo geral", "razão", "soma", "problemas"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 13,
    slug: "progressao-geometrica",
    title: "Progressão Geométrica",
    topics: ["termo geral", "razão", "soma finita", "problemas"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 14,
    slug: "principios-de-contagem",
    title: "Princípios de Contagem",
    topics: [
      "princípio fundamental da contagem",
      "árvore de possibilidades",
      "permutação",
      "arranjo",
      "combinação — sem aprofundar além do útil",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 15,
    slug: "probabilidade",
    title: "Probabilidade",
    topics: [
      "experimento",
      "espaço amostral",
      "evento",
      "probabilidade simples",
      "complementar",
      "união/interseção",
      "independência",
      "probabilidade condicional básica",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 16,
    slug: "estatistica-basica",
    title: "Estatística Básica",
    topics: [
      "população/amostra",
      "frequência absoluta/relativa",
      "média aritmética simples e ponderada",
      "mediana",
      "moda",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 17,
    slug: "dispersao-nivel-prf",
    title: "Dispersão — nível PRF",
    topics: ["amplitude", "variância e desvio-padrão em nível básico", "comparação de dispersões", "interpretação"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 18,
    slug: "tabelas-e-graficos",
    title: "Tabelas e Gráficos",
    topics: [
      "leitura",
      "interpretação",
      "comparação",
      "percentuais",
      "gráficos de barras, linhas, setores",
      "tabelas",
      "cruzamento de informações",
    ],
    priority: "Muito alta",
    weekOne: false,
  },
  {
    id: 19,
    slug: "teoria-dos-conjuntos",
    title: "Teoria dos Conjuntos",
    topics: [
      "pertinência/inclusão",
      "união",
      "interseção",
      "diferença",
      "complementar",
      "diagramas de Venn",
      "cardinalidade",
      "problemas com 2 e 3 conjuntos",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 20,
    slug: "geometria-plana",
    title: "Geometria Plana",
    topics: [
      "ângulos",
      "triângulos",
      "quadriláteros",
      "perímetro",
      "áreas",
      "circunferência/círculo",
      "Pitágoras",
      "semelhança quando necessária",
    ],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 21,
    slug: "escalas-mapas-e-plantas",
    title: "Escalas, Mapas e Plantas",
    topics: ["escala numérica", "conversão", "distâncias reais", "plantas/mapas", "proporcionalidade"],
    priority: "Muito alta para PRF",
    weekOne: false,
  },
  {
    id: 22,
    slug: "geometria-espacial",
    title: "Geometria Espacial",
    topics: ["prismas", "paralelepípedo", "cubo", "cilindro", "cone", "esfera", "áreas e volumes"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 23,
    slug: "visualizacao-espacial",
    title: "Visualização Espacial",
    topics: ["planificação", "vistas", "projeções", "cortes", "mudança de posição/orientação espacial"],
    priority: "Alta",
    weekOne: false,
  },
  {
    id: 24,
    slug: "unidades-e-metrica",
    title: "Unidades e Métrica",
    topics: ["comprimento", "área", "volume", "capacidade", "conversões", "estimativas", "problemas aplicados"],
    priority: "Alta",
    weekOne: false,
  },
];

export const prfSubjects: PrfSubject[] = [
  {
    slug: "contabilidade",
    shortName: "CONTABILIDADE",
    name: "Contabilidade",
    description: "Base patrimonial, fatos contábeis e estrutura fundamental da disciplina.",
    lessons: accountingLessons,
  },
  {
    slug: "raciocinio-logico",
    shortName: "RLM",
    name: "Raciocínio Lógico-Matemático",
    description: "Fundamentos matemáticos aplicados ao perfil de cobrança da PRF.",
    lessons: logicLessons,
  },
];

export const weekOneLessons = prfSubjects.flatMap((subject) =>
  subject.lessons
    .filter((lesson) => lesson.weekOne)
    .map((lesson) => ({ ...lesson, subjectSlug: subject.slug, subjectName: subject.name })),
);

export function getPrfSubject(subjectSlug: string) {
  return prfSubjects.find((subject) => subject.slug === subjectSlug) ?? null;
}

export function getPrfLesson(subjectSlug: string, lessonSlug: string) {
  const subject = getPrfSubject(subjectSlug);
  if (!subject) return null;
  const lesson = subject.lessons.find((item) => item.slug === lessonSlug) ?? null;
  if (!lesson) return null;
  return { subject, lesson };
}
